version: '3'
services:
  blackfire:
    container_name: blackfire
    restart: ${DOCKER_RESTART}
    image: blackfire/blackfire
    env_file:
      - .env
  mysql:
    container_name: mysql
    restart: ${DOCKER_RESTART}
    image: "mysql:5.7"
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    command: mysqld --sql_mode=""
  mailhog:
    container_name: mailhog
    restart: ${DOCKER_RESTART}
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  memcached:
    container_name: memcached
    restart: ${DOCKER_RESTART}
    image: "memcached:1-alpine"
  redis:
    container_name: redis
    restart: ${DOCKER_RESTART}
    image: "redis:4-alpine"
    ports:
      - "6379"
  apache:
    container_name: apache
    build: ./apache
    ports:
      - "80:80"
    restart: ${DOCKER_RESTART}
    volumes:
      - ./apache/sites:/usr/local/apache2/conf/sites:ro
      - ${DOCUMENTROOT}:/var/www/html:delegated
    links:
      - php56-fpm
      - php70-fpm
      - php71-fpm
    env_file:
      - .env
  php56-fpm:
    container_name: php56
    build: ./php56
    restart: ${DOCKER_RESTART}
    volumes:
      - ${DOCUMENTROOT}:/var/www/html:delegated
    env_file:
      - .env
  php70-fpm:
    container_name: php70
    build: ./php70
    restart: ${DOCKER_RESTART}
    volumes:
      - ${DOCUMENTROOT}:/var/www/html:delegated
    env_file:
      - .env
  php71-fpm:
    container_name: php71
    build: ./php71
    ports:
      - "8080:8080"
      - "3000:3000"
    restart: ${DOCKER_RESTART}
    volumes:
      - ${DOCUMENTROOT}:/var/www/html:delegated
    env_file:
      - .env
