version: '3'
services:
  web:
    container_name: pvtl-web
    build: ./php-apache
    ports:
     - "80:80"
    volumes:
     - ~/Projects/:/var/www/html/
  db:
    container_name: pvtl-db
    image: "mysql:5.7"
    environment:
     - MYSQL_ROOT_PASSWORD=dbroot
    ports:
     - "3306:3306"
    volumes:
     - ./mysql/data:/var/lib/mysql
