version: '3'
services:
  redis:
    container_name: pvtl-redis
    image: "redis:3-alpine"
    ports:
      - "6379"
  memcache:
    container_name: pvtl-memcache
    image: "memcached:1-alpine"
  web:
    container_name: pvtl-web
    build: ./php-apache
    ports:
      - "80:80"
    volumes:
      - ~/Sites/:/var/www/html/
  db:
    container_name: pvtl-db
    image: "mysql:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD=dbroot
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
  blackfire:
    container_name: pvtl-blackfire
    image: blackfire/blackfire
    environment:
        - BLACKFIRE_SERVER_ID=aed90f21-6751-4c8e-a404-8511dc67ab5d
        - BLACKFIRE_SERVER_TOKEN=4aa6b2413ee2233d614ea57d694f95a69abc61dcd4983288127dc28046ebef04
        - BLACKFIRE_LOG_LEVEL=4
