version: '3'
services:
  redis:
    container_name: redis
    image: "redis:3-alpine"
    ports:
      - "6379"
  memcached:
    container_name: memcached
    image: "memcached:1-alpine"
  web:
    container_name: web
    build: ./php-apache
    ports:
      - "80:80"
    volumes:
      - ~/Sites/:/var/www/html/
    environment:
      - APACHE_HOSTNAME=localhost
      - APACHE_PHP5CONTAINER=php5
  php5:
    container_name: php5
    build: ./php5
    ports:
      - "8056:80"
    volumes:
      - ~/Sites/:/var/www/html/
    environment:
      - APACHE_HOSTNAME=localhost
  db:
    container_name: db
    image: "mysql:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD=dbroot
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
  blackfire:
    container_name: blackfire
    image: blackfire/blackfire
    environment:
        - BLACKFIRE_SERVER_ID=xxx
        - BLACKFIRE_SERVER_TOKEN=xxx
        - BLACKFIRE_LOG_LEVEL=4
