version: '2'
services:
  web:
    build: .
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - ~/web/:/files/web/
    image: "wildcard27/dev-server"
  db:
    image: "mysql:5.6"
    image: "mysql:5.7"
    environment:
     - MYSQL_ROOT_PASSWORD=dbroot
    ports:
     - "3306:3306"
    volumes:
     - ./db_data:/var/lib/mysql
