version: '3'
services:
  blackfire:
    container_name: blackfire
    restart: ${DOCKER_RESTART}
    image: blackfire/blackfire
    env_file:
      - .env
  db:
    container_name: db
    restart: ${DOCKER_RESTART}
    image: "mysql:5.7"
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    command: mysqld --sql_mode=""
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  memcached:
    container_name: memcached
    restart: ${DOCKER_RESTART}
    image: "memcached:1-alpine"
  php5:
    container_name: php5
    restart: ${DOCKER_RESTART}
    build: ./php5
    env_file:
      - .env
    ports:
      - "8056:80"
    volumes:
      - nfsmount:/var/www/html/:delegated
  redis:
    container_name: redis
    restart: ${DOCKER_RESTART}
    image: "redis:3-alpine"
    ports:
      - "6379"
  web:
    container_name: web
    restart: ${DOCKER_RESTART}
    build: ./php-apache
    env_file:
      - .env
    ports:
      - "80:80"
      - "35729:35729"
      - "3000:3000"
      - "3001:3001"
    expose:
      - "3000"
      - "3001"
    volumes:
      - nfsmount:/var/www/html/:delegated
volumes:
  nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${DOCUMENTROOT}"
