version: '3'
services:
  # Apache ---------------------------------------------------
  apache:
    container_name: apache
    build: ./apache
    ports:
      - "80:80"
    restart: ${DOCKER_RESTART}
    volumes:
      - ./apache/sites:/usr/local/apache2/conf/sites:ro
      - ${DOCUMENTROOT}:/var/www/html:delegated
    links:
      - php56-fpm
      - php70-fpm
      - php71-fpm
      - php72-fpm
      - php73-fpm
      - php74-fpm
    env_file:
      - .env

  # Blackfire ---------------------------------------------------
  # blackfire:
  #   container_name: blackfire
  #   restart: ${DOCKER_RESTART}
  #   image: blackfire/blackfire
  #   env_file:
  #     - .env

  # Mailhog ---------------------------------------------------
  mailhog:
    container_name: mailhog
    restart: ${DOCKER_RESTART}
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  # Memcached ---------------------------------------------------
  memcached:
    container_name: memcached
    restart: ${DOCKER_RESTART}
    image: "memcached:1-alpine"

  # MySQL ---------------------------------------------------
  mysql:
    container_name: mysql
    restart: ${DOCKER_RESTART}
    image: "mysql:5.7"
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    command: mysqld --sql_mode=""

  # PHP 5.6 ---------------------------------------------------
  php56-fpm:
    container_name: php56
    build:
      context: ./php
      dockerfile: ./56/Dockerfile
    restart: ${DOCKER_RESTART}
    volumes:
      - ${DOCUMENTROOT}:/var/www/html:delegated
    env_file:
      - .env

  # PHP 7.0 ---------------------------------------------------
  php70-fpm:
    container_name: php70
    build:
      context: ./php
      dockerfile: ./70/Dockerfile
    restart: ${DOCKER_RESTART}
    volumes:
      - ${DOCUMENTROOT}:/var/www/html:delegated
    env_file:
      - .env

  # PHP 7.1 ---------------------------------------------------
  php71-fpm:
    container_name: php71
    build:
      context: ./php
      dockerfile: ./71/Dockerfile
    restart: ${DOCKER_RESTART}
    volumes:
      - ${DOCUMENTROOT}:/var/www/html:delegated
    env_file:
      - .env

  # PHP 7.2 ---------------------------------------------------
  php72-fpm:
    container_name: php72
    build:
      context: ./php
      dockerfile: ./72/Dockerfile
    restart: ${DOCKER_RESTART}
    volumes:
      - ${DOCUMENTROOT}:/var/www/html:delegated
    env_file:
      - .env

  # PHP 7.3 ---------------------------------------------------
  php73-fpm:
    container_name: php73
    build:
      context: ./php
      dockerfile: ./73/Dockerfile
    restart: ${DOCKER_RESTART}
    volumes:
      - ${DOCUMENTROOT}:/var/www/html:delegated
    env_file:
      - .env

  # PHP 7.4 ---------------------------------------------------
  php74-fpm:
    container_name: php74
    build:
      context: ./php
      dockerfile: ./74/Dockerfile
    restart: ${DOCKER_RESTART}
    ports:
      - "8080:8080" # Browser Sync
      - "3000:3000" # Browser Sync
    volumes:
      - ${DOCUMENTROOT}:/var/www/html:delegated
    env_file:
      - .env

  # Redis ---------------------------------------------------
  redis:
    container_name: redis
    restart: ${DOCKER_RESTART}
    image: "redis:5-alpine"
    ports:
      - "6379:6379"
